# all :
# 	$(CXX) ./main.cpp ../PathFinder.cpp \
# 		./Config.cpp ./content.cpp \
# 		./print.cpp ./utils.hpp ./ft_error.cpp ./ft_config_split.cpp \
# 		./ft_process_print.cpp

CXXFLAGS := -g3

all :
	rm -rf a.out a.out.dSYM utils.hpp.gch
	$(CXX) $(CXXFLAGS) ./main.cpp ../PathFinder.cpp \
		./Config.cpp ./content.cpp \
		./print.cpp ./utils.hpp ./ft_error.cpp ./ft_config_split.cpp \
		./ft_process_print.cpp